name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if exist requirements.txt pip install -r requirements.txt

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name SpeedyDot main.py

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: SpeedyDot-exe
        path: dist/SpeedyDot.exe
